//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler hatalı davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.StockModel")]
    public partial class Stock : object
    {
        
        private string DescriptionField;
        
        private int IdField;
        
        private System.DateTime LastUpdatedField;
        
        private string NameField;
        
        private decimal PriceField;
        
        private StockService.StockPriceHistory[] PriceHistoryField;
        
        private string SymbolField;
        
        private int TotalSharesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated
        {
            get
            {
                return this.LastUpdatedField;
            }
            set
            {
                this.LastUpdatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.StockPriceHistory[] PriceHistory
        {
            get
            {
                return this.PriceHistoryField;
            }
            set
            {
                this.PriceHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalShares
        {
            get
            {
                return this.TotalSharesField;
            }
            set
            {
                this.TotalSharesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockPriceHistory", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models")]
    public partial class StockPriceHistory : object
    {
        
        private int IdField;
        
        private decimal PriceField;
        
        private System.DateTime RecordedAtField;
        
        private StockService.Stock StockField;
        
        private int StockIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RecordedAt
        {
            get
            {
                return this.RecordedAtField;
            }
            set
            {
                this.RecordedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.Stock Stock
        {
            get
            {
                return this.StockField;
            }
            set
            {
                this.StockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockId
        {
            get
            {
                return this.StockIdField;
            }
            set
            {
                this.StockIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockResponse", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.StockModel")]
    public partial class StockResponse : object
    {
        
        private int PageNumberField;
        
        private int PageSizeField;
        
        private StockService.Stock[] StocksField;
        
        private int TotalCountField;
        
        private int TotalPagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.Stock[] Stocks
        {
            get
            {
                return this.StocksField;
            }
            set
            {
                this.StocksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalCount
        {
            get
            {
                return this.TotalCountField;
            }
            set
            {
                this.TotalCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateUserRequest", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.UserModel")]
    public partial class CreateUserRequest : object
    {
        
        private decimal InitialBalanceField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InitialBalance
        {
            get
            {
                return this.InitialBalanceField;
            }
            set
            {
                this.InitialBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateUserResponse", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.UserModel")]
    public partial class CreateUserResponse : object
    {
        
        private StockService.User CreatedUserField;
        
        private string MessageField;
        
        private int SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.User CreatedUser
        {
            get
            {
                return this.CreatedUserField;
            }
            set
            {
                this.CreatedUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.UserModel")]
    public partial class User : object
    {
        
        private decimal BalanceField;
        
        private System.DateTime CreatedAtField;
        
        private string EmailField;
        
        private int IdField;
        
        private string PasswordHashField;
        
        private StockService.UserStock[] UserStocksField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash
        {
            get
            {
                return this.PasswordHashField;
            }
            set
            {
                this.PasswordHashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.UserStock[] UserStocks
        {
            get
            {
                return this.UserStocksField;
            }
            set
            {
                this.UserStocksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStock", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models")]
    public partial class UserStock : object
    {
        
        private int IdField;
        
        private decimal PurchasePriceField;
        
        private System.DateTime PurchasedAtField;
        
        private int QuantityField;
        
        private int StockIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchasePrice
        {
            get
            {
                return this.PurchasePriceField;
            }
            set
            {
                this.PurchasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PurchasedAt
        {
            get
            {
                return this.PurchasedAtField;
            }
            set
            {
                this.PurchasedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockId
        {
            get
            {
                return this.StockIdField;
            }
            set
            {
                this.StockIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.UserModel")]
    public partial class LoginRequest : object
    {
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResponse", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.UserModel")]
    public partial class LoginResponse : object
    {
        
        private decimal BalanceField;
        
        private string EmailField;
        
        private int SuccessField;
        
        private int UserIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuyStockRequest", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.StockModel")]
    public partial class BuyStockRequest : object
    {
        
        private int QuantityField;
        
        private int StockIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockId
        {
            get
            {
                return this.StockIdField;
            }
            set
            {
                this.StockIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuyStockResponse", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.StockModel")]
    public partial class BuyStockResponse : object
    {
        
        private decimal ExecutedPriceField;
        
        private string MessageField;
        
        private decimal NewBalanceField;
        
        private bool SuccessField;
        
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExecutedPrice
        {
            get
            {
                return this.ExecutedPriceField;
            }
            set
            {
                this.ExecutedPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NewBalance
        {
            get
            {
                return this.NewBalanceField;
            }
            set
            {
                this.NewBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortfolioResponse", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.PortfolioModel")]
    public partial class PortfolioResponse : object
    {
        
        private StockService.PortfolioItem[] ItemsField;
        
        private string MessageField;
        
        private bool SuccessField;
        
        private StockService.PortfolioSummary SummaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.PortfolioItem[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.PortfolioSummary Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortfolioSummary", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.PortfolioModel")]
    public partial class PortfolioSummary : object
    {
        
        private decimal DailyProfitLossField;
        
        private StockService.PortfolioItem[] ItemsField;
        
        private decimal TotalInvestmentField;
        
        private decimal TotalPortfolioValueField;
        
        private decimal TotalProfitLossField;
        
        private decimal TotalProfitLossPercentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DailyProfitLoss
        {
            get
            {
                return this.DailyProfitLossField;
            }
            set
            {
                this.DailyProfitLossField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.PortfolioItem[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalInvestment
        {
            get
            {
                return this.TotalInvestmentField;
            }
            set
            {
                this.TotalInvestmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPortfolioValue
        {
            get
            {
                return this.TotalPortfolioValueField;
            }
            set
            {
                this.TotalPortfolioValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalProfitLoss
        {
            get
            {
                return this.TotalProfitLossField;
            }
            set
            {
                this.TotalProfitLossField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalProfitLossPercent
        {
            get
            {
                return this.TotalProfitLossPercentField;
            }
            set
            {
                this.TotalProfitLossPercentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortfolioItem", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.PortfolioModel")]
    public partial class PortfolioItem : object
    {
        
        private decimal CurrentPriceField;
        
        private decimal CurrentValueField;
        
        private string DescriptionField;
        
        private string NameField;
        
        private decimal ProfitLossField;
        
        private decimal ProfitLossPercentField;
        
        private decimal PurchasePriceField;
        
        private System.DateTime PurchasedAtField;
        
        private int QuantityField;
        
        private string SymbolField;
        
        private decimal TotalCostField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentPrice
        {
            get
            {
                return this.CurrentPriceField;
            }
            set
            {
                this.CurrentPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentValue
        {
            get
            {
                return this.CurrentValueField;
            }
            set
            {
                this.CurrentValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProfitLoss
        {
            get
            {
                return this.ProfitLossField;
            }
            set
            {
                this.ProfitLossField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProfitLossPercent
        {
            get
            {
                return this.ProfitLossPercentField;
            }
            set
            {
                this.ProfitLossPercentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchasePrice
        {
            get
            {
                return this.PurchasePriceField;
            }
            set
            {
                this.PurchasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PurchasedAt
        {
            get
            {
                return this.PurchasedAtField;
            }
            set
            {
                this.PurchasedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCost
        {
            get
            {
                return this.TotalCostField;
            }
            set
            {
                this.TotalCostField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionHistoryResponse", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.TransactionMode" +
        "l")]
    public partial class TransactionHistoryResponse : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        private StockService.TransactionHistory[] TransactionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockService.TransactionHistory[] Transactions
        {
            get
            {
                return this.TransactionsField;
            }
            set
            {
                this.TransactionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionHistory", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.TransactionMode" +
        "l")]
    public partial class TransactionHistory : object
    {
        
        private int IdField;
        
        private decimal PriceField;
        
        private int QuantityField;
        
        private string StockNameField;
        
        private string SymbolField;
        
        private decimal TotalAmountField;
        
        private System.DateTime TransactionDateField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockName
        {
            get
            {
                return this.StockNameField;
            }
            set
            {
                this.StockNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate
        {
            get
            {
                return this.TransactionDateField;
            }
            set
            {
                this.TransactionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SellRequest", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models")]
    public partial class SellRequest : object
    {
        
        private decimal PriceField;
        
        private int QuantityField;
        
        private string SymbolField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SellStockResponse", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.StockModel")]
    public partial class SellStockResponse : object
    {
        
        private string MessageField;
        
        private decimal NewBalanceField;
        
        private bool SuccessField;
        
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NewBalance
        {
            get
            {
                return this.NewBalanceField;
            }
            set
            {
                this.NewBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuyOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.OrderModel")]
    public partial class BuyOrderRequest : object
    {
        
        private decimal MaxPriceField;
        
        private int QuantityField;
        
        private int StockIdField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MaxPrice
        {
            get
            {
                return this.MaxPriceField;
            }
            set
            {
                this.MaxPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockId
        {
            get
            {
                return this.StockIdField;
            }
            set
            {
                this.StockIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResult", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.OrderModel")]
    public partial class OrderResult : object
    {
        
        private string MessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SellOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.OrderModel")]
    public partial class SellOrderRequest : object
    {
        
        private decimal MinPriceField;
        
        private int QuantityField;
        
        private int StockIdField;
        
        private string SymbolField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MinPrice
        {
            get
            {
                return this.MinPriceField;
            }
            set
            {
                this.MinPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StockId
        {
            get
            {
                return this.StockIdField;
            }
            set
            {
                this.StockIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurchaseDetail", Namespace="http://schemas.datacontract.org/2004/07/StockExchange.Core.Models.OrderModel")]
    public partial class PurchaseDetail : object
    {
        
        private decimal CurrentPriceField;
        
        private decimal CurrentValueField;
        
        private decimal ProfitLossField;
        
        private decimal PurchasePriceField;
        
        private System.DateTime PurchasedAtField;
        
        private int QuantityField;
        
        private decimal TotalCostField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentPrice
        {
            get
            {
                return this.CurrentPriceField;
            }
            set
            {
                this.CurrentPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentValue
        {
            get
            {
                return this.CurrentValueField;
            }
            set
            {
                this.CurrentValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProfitLoss
        {
            get
            {
                return this.ProfitLossField;
            }
            set
            {
                this.ProfitLossField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PurchasePrice
        {
            get
            {
                return this.PurchasePriceField;
            }
            set
            {
                this.PurchasePriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PurchasedAt
        {
            get
            {
                return this.PurchasedAtField;
            }
            set
            {
                this.PurchasedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCost
        {
            get
            {
                return this.TotalCostField;
            }
            set
            {
                this.TotalCostField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockService.IStockService")]
    public interface IStockService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetStockPrice", ReplyAction="http://tempuri.org/IStockService/GetStockPriceResponse")]
        System.Threading.Tasks.Task<decimal> GetStockPriceAsync(string stockSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetStocks", ReplyAction="http://tempuri.org/IStockService/GetStocksResponse")]
        System.Threading.Tasks.Task<StockService.Stock[]> GetStocksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetStocksPaged", ReplyAction="http://tempuri.org/IStockService/GetStocksPagedResponse")]
        System.Threading.Tasks.Task<StockService.StockResponse> GetStocksPagedAsync(int pageNumber, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetStock", ReplyAction="http://tempuri.org/IStockService/GetStockResponse")]
        System.Threading.Tasks.Task<StockService.Stock> GetStockAsync(string stockSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/CreateUser", ReplyAction="http://tempuri.org/IStockService/CreateUserResponse")]
        System.Threading.Tasks.Task<StockService.CreateUserResponse> CreateUserAsync(StockService.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/Login", ReplyAction="http://tempuri.org/IStockService/LoginResponse")]
        System.Threading.Tasks.Task<StockService.LoginResponse> LoginAsync(StockService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetPriceHistoryWithSymbol", ReplyAction="http://tempuri.org/IStockService/GetPriceHistoryWithSymbolResponse")]
        System.Threading.Tasks.Task<StockService.StockPriceHistory[]> GetPriceHistoryWithSymbolAsync(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/BuyStock", ReplyAction="http://tempuri.org/IStockService/BuyStockResponse")]
        System.Threading.Tasks.Task<StockService.BuyStockResponse> BuyStockAsync(StockService.BuyStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetPortfolio", ReplyAction="http://tempuri.org/IStockService/GetPortfolioResponse")]
        System.Threading.Tasks.Task<StockService.PortfolioResponse> GetPortfolioAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetTransactionHistory", ReplyAction="http://tempuri.org/IStockService/GetTransactionHistoryResponse")]
        System.Threading.Tasks.Task<StockService.TransactionHistoryResponse> GetTransactionHistoryAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/SellStock", ReplyAction="http://tempuri.org/IStockService/SellStockResponse")]
        System.Threading.Tasks.Task<StockService.SellStockResponse> SellStockAsync(StockService.SellRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/AddBuyOrder", ReplyAction="http://tempuri.org/IStockService/AddBuyOrderResponse")]
        System.Threading.Tasks.Task<StockService.OrderResult> AddBuyOrderAsync(StockService.BuyOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/AddSellOrder", ReplyAction="http://tempuri.org/IStockService/AddSellOrderResponse")]
        System.Threading.Tasks.Task<StockService.OrderResult> AddSellOrderAsync(StockService.SellOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/GetUserStockPurchaseHistory", ReplyAction="http://tempuri.org/IStockService/GetUserStockPurchaseHistoryResponse")]
        System.Threading.Tasks.Task<StockService.PurchaseDetail[]> GetUserStockPurchaseHistoryAsync(int userId, string stockSymbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IStockServiceChannel : StockService.IStockService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<StockService.IStockService>, StockService.IStockService
    {
        
        /// <summary>
        /// Hizmet uç noktasını yapılandırmak için bu kısmi metodu uygulayın.
        /// </summary>
        /// <param name="serviceEndpoint">Yapılandırılacak uç nokta</param>
        /// <param name="clientCredentials">İstemci kimlik bilgileri</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StockServiceClient() : 
                base(StockServiceClient.GetDefaultBinding(), StockServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IStockService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StockServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(StockServiceClient.GetBindingForEndpoint(endpointConfiguration), StockServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StockServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StockServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StockServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StockServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<decimal> GetStockPriceAsync(string stockSymbol)
        {
            return base.Channel.GetStockPriceAsync(stockSymbol);
        }
        
        public System.Threading.Tasks.Task<StockService.Stock[]> GetStocksAsync()
        {
            return base.Channel.GetStocksAsync();
        }
        
        public System.Threading.Tasks.Task<StockService.StockResponse> GetStocksPagedAsync(int pageNumber, int pageSize)
        {
            return base.Channel.GetStocksPagedAsync(pageNumber, pageSize);
        }
        
        public System.Threading.Tasks.Task<StockService.Stock> GetStockAsync(string stockSymbol)
        {
            return base.Channel.GetStockAsync(stockSymbol);
        }
        
        public System.Threading.Tasks.Task<StockService.CreateUserResponse> CreateUserAsync(StockService.CreateUserRequest request)
        {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockService.LoginResponse> LoginAsync(StockService.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockService.StockPriceHistory[]> GetPriceHistoryWithSymbolAsync(string symbol)
        {
            return base.Channel.GetPriceHistoryWithSymbolAsync(symbol);
        }
        
        public System.Threading.Tasks.Task<StockService.BuyStockResponse> BuyStockAsync(StockService.BuyStockRequest request)
        {
            return base.Channel.BuyStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockService.PortfolioResponse> GetPortfolioAsync(int userId)
        {
            return base.Channel.GetPortfolioAsync(userId);
        }
        
        public System.Threading.Tasks.Task<StockService.TransactionHistoryResponse> GetTransactionHistoryAsync(int userId)
        {
            return base.Channel.GetTransactionHistoryAsync(userId);
        }
        
        public System.Threading.Tasks.Task<StockService.SellStockResponse> SellStockAsync(StockService.SellRequest request)
        {
            return base.Channel.SellStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockService.OrderResult> AddBuyOrderAsync(StockService.BuyOrderRequest request)
        {
            return base.Channel.AddBuyOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockService.OrderResult> AddSellOrderAsync(StockService.SellOrderRequest request)
        {
            return base.Channel.AddSellOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockService.PurchaseDetail[]> GetUserStockPurchaseHistoryAsync(int userId, string stockSymbol)
        {
            return base.Channel.GetUserStockPurchaseHistoryAsync(userId, stockSymbol);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStockService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStockService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5000/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("\'{0}\' adlı uç nokta bulunamadı.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StockServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IStockService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StockServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IStockService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IStockService,
        }
    }
}
